language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1   # enables coverage+coveralls reporting
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
