dist: trusty
language: perl
os:
  - linux
jobs:
  include:
    - perl: 5.30
      after_success:
      - cover -test -report coveralls
    - perl: 5.24
    - perl: 5.12
before_install:
  - cpanm --notest Module::Build
  - cpanm --notest BioX::Seq
  - cpanm --notest Devel::Cover
  - cpanm --notest Devel::Cover::Report::Coveralls
